### ISSUE TITLE
IGKC is nice 

### ISSUE THREAD

**Issue by jeitziner** [sib-swiss/single-cell-training#33]
We should check in which PC IGKC is appearing as when you use 5 PCs the group disappears this is a nice illustration of what PCs are for.

**Comment by GeertvanGeest** [comment]
Is this still an issue?

**Comment by taniawyss** [comment]
> Is this still an issue?

I think the issue can be solved

**Comment by jeitziner** [comment]
It was no Issue was just a cool thing to show. And IGKC is associated with PC11 so we saw that we needed at least 11 PCs to see the cluster forming. Was just a nice illustration :-)

**Comment by jeitziner** [comment]
We added it in the corrections!

**Comment by GeertvanGeest** [comment]
Awesome
