### ISSUE TITLE
Bug monocle3 at step "cluster_cells"

### ISSUE THREAD

**Issue by taniawyss** [sib-swiss/single-cell-training#48]
seu_int_monocl <- monocle3::cluster_cells(seu_int_monocl, resolution=0.0002)

Output:
Error in leidenbase::leiden_find_partition(graph_result[["g"]], partition_type = partition_type,  
REAL() can only be applied to a 'numeric', not a 'NULL'

Replace by:
seu_int_monocl <- monocle3::cluster_cells(seu_int_monocl, cluster_method = "louvain")

Others encountered the same issue, linked to R 4.3?
https://github.com/cole-trapnell-lab/monocle3/issues/666

**Comment by gengjie2000** [comment]
Thank you for your help. This method has solved my problem！

**Comment by GeertvanGeest** [comment]
Should be fixed in 311346c.
